Module3 task1
htmlacademy-ecmascript/1493681-cinemaddict-14 pull request #5
Opened 2021-04-11 13:07 UTC by NikolayUsov

2021-04-12 20:16 UTC, obzhorash requested changes

2021-04-12 20:16 UTC, obzhorash commented on public/index.html
> +<body class="hidden-popuphhh">
hidden-popuphhh ?)

2021-04-12 20:16 UTC, obzhorash commented on src/main.js
> +    popUp .getElement().remove();
Не уверен что это работает,проверь

2021-04-13 07:50 UTC, NikolayUsov commented on src/main.js
> +    popUp .getElement().remove();
Проверил, попап скрывается и по  клику и по esc

2021-04-13 20:25 UTC, merged