init: create abstract class
htmlacademy-ecmascript/1493681-cinemaddict-14 pull request #6
Opened 2021-04-14 09:59 UTC by NikolayUsov

2021-04-14 19:40 UTC, obzhorash requested changes

2021-04-14 19:40 UTC, obzhorash commented on src/utils/profile-util.js
> +      if (USER_STATUS[key].FROM <= number && number <= USER_STATUS[key].TO) {
зачем from to, лучше свитчём сделать

2021-04-14 19:40 UTC, obzhorash commented on src/utils/profile-util.js
> +  for (let i = 0; i < filmData.length; i++) {
лучшe forEach

2021-04-15 20:06 UTC, NikolayUsov commented on src/utils/profile-util.js
> +      if (USER_STATUS[key].FROM <= number && number <= USER_STATUS[key].TO) {
я таки не понял как это реализовать и почему список хуже? Если прописывать свитч то получается будет кучу условий и еще полно магических чисел. Мне видеться мапа удобнее, если что не понял, покажи как нужно.

2021-04-15 20:12 UTC, merged